api = "0.10"

[buildpack]
id = "dev.supervise.buildpacks"
version = "1.0.0"
name = "Supervise Buildpacks"
homepage = "https://supervise.dev"

[[order]]
[[order.group]]
id = "dev.supervise.pkgx"
version = "1.0.0"

[[order.group]]
id = "dev.supervise.caddy"
version = "1.0.0"

[[order.group]]
id = "dev.supervise.ttyd"
version = "1.0.0"

[[order.group]]
id = "dev.supervise.runtime"
version = "1.0.0"